### ISSUE TITLE
Error in BigIntegers.Primes

### ISSUE THREAD

**Issue by majorL** [rvelthuis/BigNumbers#1]
I'm getting an error when attempting to compile velthuis.bitintegers.primes on the function NextProbablePrime.  Errors on BigInteger.Two.

You have a global variable "Two" declared as a BigInteger, and initialize it to 2, and you also have a local variable Two also declared as a BigInteger.  But BigInteger class does not have a method Two.

**Comment by rvelthuis** [comment]
I'll take a look. It should be there, actually.

**Comment by rvelthuis** [comment]
Corrected
