### ISSUE TITLE
Results of Divide, Sqrt etc. for precise numbers is zero

### ISSUE THREAD

**Issue by Safrad** [rvelthuis/BigNumbers#11]
Happens if BigDecimal.DefaultPrecision is less then number precision.
If default precision is 64 then BigDecimal.Sqrt of number with 65 or more digits return always 0. "Sqrt(Pi) = 0"

Workaround:
call Sqrt with parameter Max(DefaultPrecision and Number.Precision)

The same problem is for division.
Happens for 10000 digit precison constants i.e. "Pi / 2 = 0"
if Pi decimal places >DefaultPrecision

Maybe it is a feature? :-)

**Comment by rvelthuis** [comment]
No, certainly not a feature. Must look into it.

**Comment by rvelthuis** [comment]
Solved. Now good for precisions higher than default too.
