### ISSUE TITLE
BigDecimal.Sqrt always gets divide by zero error.

### ISSUE THREAD

**Issue by chesterw** [rvelthuis/BigNumbers#2]
I love Bigintegers and BigDecimals!

 I can't get BigDecimal.Sqrt to work: always get divide by zero error. Here is my humble attempt:
 A := '123.456';
 writeln('>> 1 ',A.ToPlainString);
 B := BigDecimal.Sqrt(A);
 writeln('>> 2');
 --- Of course A and B are type BigDecimal. I must be doing something wrong. The same code for BigInteger works fine.

After a little digging:
 I changed Veltius.BigDecimals.pas, function BigDecimal.Sqrt(Precision: Integer): BigDecimal;
 from:
 while (Result * Result - Self).Abs >= Epsilon do
 to:
 while ((Result * Result - Self).Abs >= Epsilon) and (Result < 0.0)

This seems to work for me.

**Comment by rvelthuis** [comment]
I added your suggestion (well, by checking for `Result.IsZero`) and found out that `FHalf` and `FOneTenth` were not initialized. `Sqrt()` uses `Half`.  This used to be a local variable, but I decided to make it a property. Just forgot to initialize it and `OneTenth`. Added those and now it seems to work. Thanks for the heads-up!

**Comment by chesterw** [comment]
Thank you so much!  It works fine now.  I have used BigIntegers and
BigDecimals units for some time now: Some programs: prime numbers and sums
of factors databases out to hundreds of millions with remarkable speed.
Again, thank you.
