### ISSUE TITLE
Tryng to calculate modulus, dies after correct result into FastMM error

### ISSUE THREAD

**Issue by TommiPrami** [rvelthuis/BigNumbers#4]
We use latest Delphi(10.2 Tokyo and latest FastMM4

Code is following 

function BigIntegerStrMod(const ABigInteger: string; const Adivider: Integer): Integer;
var
  LBigInt: BigInteger;
  LDivisor: BigInteger;
  LReminder: BigInteger;
begin
  // Alkuarvo
  if not BigInteger.TryParse(ABigInteger, LBigInt) then
    raise Exception.CreateFmt('Virheellinen numero %s', [ABigInteger]);
  LDivisor := BigInteger.Create(Adivider);
  LReminder := BigInteger.Create(0);

  // Lasketana ja Palautetaan
  LReminder := LBigInt mod LDivisor;
  Result := LReminder.AsInteger;
end;

At last line when some cleanup happens we get FastMM error

---------------------------
STCommon.UnitTests.exe: Memory Error Detected
---------------------------
FastMM has detected an error during a FreeMem operation. The block footer has been corrupted. 

The block size is: 40

This block was allocated by thread 0x54E8, and the stack trace (return addresses) at the time was:

43BDFA [FastMM4][DebugAllocMem$qqri]

409C86 [System.pas][System][AllocMem$qqri][4688]

E2E558 [Velthuis.BigIntegers.pas][Velthuis.BigIntegers][Bigintegers.AllocNewMagnitude$qqrrpvi][9265]

E2E5A5 [Velthuis.BigIntegers.pas][Velthuis.BigIntegers][Bigintegers.BigInteger.MakeSize$qqri][9274]

E2AF40 [Velthuis.BigIntegers.pas][Velthuis.BigIntegers][Bigintegers.BigInteger.TryParse$qqrx20System.UnicodeStringzcr31Velthuis.Bigintegers.BigInteger][5190]

409CBA [System.pas][System][@GetMem$qqri][4745]

E2AE55 [Velthuis.BigIntegers.pas][Velthuis.BigIntegers][Bigintegers.BigInteger.TryParse$qqrx20System.UnicodeStringr31Velthuis.Bigintegers.BigInteger][5171]

4105E6 [System.pas][System][@FinalizeArray$qqrpvt1ui][32099]

4104A1 [System.pas][System][@FinalizeRecord$qqrpvt1][31777]

E33CE0 [STCommon.PankkiUtils.pas][STCommon.PankkiUtils][Pankkiutils.BigIntegerStrMod$qqrx20System.UnicodeStringxi][1075]

E33F01 [STCommon.PankkiUtils.pas][STCommon.PankkiUtils][Pankkiutils.TarkistaRFViite$qqrx20System.UnicodeString][1127]

The block is currently used for an object of class: Unknown

The allocation number is: 589545

The block was previously freed by thread 0x54E8, and the stack trace (return addresses) at the time was:

43BD75 [FastMM4][DebugReallocMem$qqrpvi]

409CF7 [System.pas][System][@ReallocMem$qqrrpvi][4867]

40FB19 [System.pas][System][@UStrSetLength$qqrr20System.UnicodeStringi][29850]

40FB9A [System.pas][System][@UStrCat$qqrr20System.UnicodeStringx20System.UnicodeString][29963]

E33C4D [STCommon.PankkiUtils.pas][STCommon.PankkiUtils][Pankkiutils.RFReferenceCharsToNumbers$qqrx20System.UnicodeString][1064]

E33E5C [STCommon.PankkiUtils.pas][STCommon.PankkiUtils][Pankkiutils.NormalizeRFReference$qqrr20System.UnicodeString][1096]

E33EDA [STCommon.PankkiUtils.pas][STCommon.PankkiUtils][Pankkiutils.TarkistaRFViite$qqrx20System.UnicodeString][1120]

4105D5 [System.pas][System][@FinalizeArray$qqrpvt1ui][32070]

E3BD9D [STCommon.PankkiUtils.DUnitX.pas][STCommon.PankkiUtils.DUnitX][Pankkiutils.Dunitx.TSTCommonPankkiUtilsTests.TarkistaRFViiteTest$qqrx20System.UnicodeStringxo][47]

4B6810 [System.Rtti.pas][System.Rtti][Rtti.RawInvoke$qqrpvp23System.Rtti.TParamBlock][7750]

4B6C14 [System.Rtti.pas][System.Rtti][Rtti.Invoke$qqrpvx42System.%DynamicArray$18System.Rtti.TValue%24System.Typinfo.TCallConvp24System.Typinfo.TTypeInfooo][7972]

The current thread ID is 0x54E8, and the stack trace (return addresses) leading to this error is:

411A1C [System.pas][System][@DynArrayClear$qqrrpvpv][35224]

4105E6 [System.pas][System][@FinalizeArray$qqrpvt1ui][32099]

4104A1 [System.pas][System][@FinalizeRecord$qqrpvt1][31777]

4105C5 [System.pas][System][@FinalizeArray$qqrpvt1ui][32058]

E33D58 [STCommon.PankkiUtils.pas][STCommon.PankkiUtils][Pankkiutils.BigIntegerStrMod$qqrx20System.UnicodeStringxi][1083]

E33F01 [STCommon.PankkiUtils.pas][STCommon.PankkiUtils][Pankkiutils.TarkistaRFViite$qqrx20System.UnicodeString][1127]

E3BD9D [STCommon.PankkiUtils.DUnitX.pas][STCommon.PankkiUtils.DUnitX][Pankkiutils.Dunitx.TSTCommonPankkiUtilsTests.TarkistaRFViiteTest$qqrx20System.UnicodeStringxo][47]

4B6810 [System.Rtti.pas][System.Rtti][Rtti.RawInvoke$qqrpvp23System.Rtti.TParamBlock][7750]

4B6C14 [System.Rtti.pas][System.Rtti][Rtti.Invoke$qqrpvx42System.%DynamicArray$18System.Rtti.TValue%24System.Typinfo.TCallConvp24System.Typinfo.TTypeInfooo][7972]

4ADAA5 [System.Rtti.pas][System.Rtti][Rtti.TRttiInstanceMethodEx.DispatchInvoke$qqrrx18System.Rtti.TValuepx18System.Rtti.TValuexi][5883]

4B6FBF [System.Rtti.pas][System.Rtti][Rtti.TRttiMethod.Invoke$qqrp14System.TObjectpx18System.Rtti.TValuexi][9212]

Current memory dump of 256 bytes starting at pointer address 7EF84C30:

00 00 00 00 08 00 00 00 D1 D6 39 E5 57 28 D4 21 5A 80 29 00 00 00 00 00 00 00 00 00 00 00 00 00

00 00 00 00 00 00 00 00 00 00 00 00 80 80 80 80 80 80 80 80 80 80 80 80 00 00 00 00 10 11 F8 7E

00 00 00 00 00 00 00 00 14 BA 43 00 00 00 00 00 66 FD 08 00 BA 9C 40 00 6B C7 40 00 8A CF 40 00

DF 40 5E 00 74 C7 40 00 69 45 41 00 26 3F 5E 00 88 9E 5E 00 B2 9F 5E 00 28 33 41 00 D1 91 5F 00

E8 54 00 00 E8 54 00 00 89 C7 40 00 D5 CF 40 00 94 01 53 00 03 C9 40 00 04 4E 52 00 9C 65 52 00

F1 50 52 00 8B F6 75 00 A0 52 76 00 F6 4E 52 00 22 4A 52 00 34 00 00 00 AC 9A 4F 00 27 55 91 86

34 12 5E 00 00 00 00 00 01 00 00 00 34 0F 5E 00 90 40 5E 00 F0 4C F8 7E 9C 40 5E 00 F0 4C F8 7E

70 E4 FB 7E DC 94 E5 00 00 00 00 00 00 00 00 00 00 00 00 00 D8 AA 6E 79 00 00 00 00 10 11 F8 7E

.  .  .  .  .  .  .  .  Ñ  Ö  9  å  W  (  Ô  !  Z  €  )  .  .  .  .  .  .  .  .  .  .  .  .  .

.  .  .  .  .  .  .  .  .  .  .  .  €  €  €  €  €  €  €  €  €  €  €  €  .  .  .  .  .  .  ø  ~

.  .  .  .  .  .  .  .  .  º  C  .  .  .  .  .  f  ý  .  .  º  œ  @  .  k  Ç  @  .  Š  Ï  @  .

ß  @  ^  .  t  Ç  @  .  i  E  A  .  &  ?  ^  .  ˆ  ž  ^  .  ²  Ÿ  ^  .  (  3  A  .  Ñ  ‘  _  .

è  T  .  .  è  T  .  .  ‰  Ç  @  .  Õ  Ï  @  .  ”  .  S  .  .  É  @  .  .  N  R  .  œ  e  R  .

ñ  P  R  .  ‹  ö  u  .     R  v  .  ö  N  R  .  "  J  R  .  4  .  .  .  ¬  š  O  .  '  U  ‘  †

4  .  ^  .  .  .  .  .  .  .  .  .  4  .  ^  .    @  ^  .  ð  L  ø  ~  œ  @  ^  .  ð  L  ø  ~

p  ä  û  ~  Ü  ”  å  .  .  .  .  .  .  .  .  .  .  .  .  .  Ø  ª  n  y  .  .  .  .  .  .  ø  ~

---------------------------
OK   
---------------------------

And  then exception 

---------------------------
Debugger Exception Notification
---------------------------
Project STCommon.UnitTests.exe raised exception class EInvalidPointer with message 'Invalid pointer operation'.
---------------------------
Break   Continue   Help   
---------------------------

Is My Code broken, is there something I need to do etc...

**Comment by TommiPrami** [comment]
From madExcept

disassembling:
[...]
0040fbcf      mov     edx, [edx]
0040fbd1      push    eax
0040fbd2      call    -$1583 ($40e654)       ; System.@FinalizeArray
0040fbd2
0040fbd7      pop     eax
0040fbd2
0040fbd8    loc_40fbd8:
0040fbd8      sub     eax, 8
0040fbdb      call    -$858c ($407654)       ; System.@FreeMem
0040fbdb
0040fbe0    > pop     eax
0040fbdb
0040fbe1    loc_40fbe1:
0040fbe1      ret

**Comment by TommiPrami** [comment]
[FastMM4Options.zip](https://github.com/rvelthuis/BigNumbers/files/1189514/FastMM4Options.zip)

Tried this also in product, behaves identically as the Unit-test project

Is this an bug, or FastMM option problem, don't know. Wait a sec, I'll try build product in release mode...

Works in a release mode, so it must be FastMM check.

Don't know is it because of FastMM is hyper sensitive, or is there actually an bug... I'll attach

 my FastMM settings in this message.

**Comment by TommiPrami** [comment]
Tested this with fresh project with FastMM4 in debug mode and the problem is the same. So it is not relat to projects it supposed to go in.

Have no idea so far how to prevent FastMM to go haywire on this. 

I am all ears ;)

**Comment by TommiPrami** [comment]
Seems that it could actually be an bug : http://techqa.info/programming/question/10329940/fastmm4-says-

FastMM in full Debug mode allocates bit more memory to the block and adds known value in that part. In FreeMem it checks if the known value still there, if not, that error is raised. So if memory is written past it's bounds it can be detected when it freed.

**Comment by TommiPrami** [comment]
Error still exists. Checked this with the very latest version from repository.

**Comment by rvelthuis** [comment]
I tried with this simple test program. No problems in either Win32 or Win64. What are the input and output you get?

    program BigIntStrModIssue;

    {$APPTYPE CONSOLE}

    {$R *.res}

    uses
      System.SysUtils,
      Velthuis.BigIntegers;

    function BigIntegerStrMod(const ABigInteger: string; const Adivider: Integer): Integer;
    var
      LBigInt: BigInteger;
      LDivisor: BigInteger;
      LRemainder: BigInteger;
    begin
      // Alkuarvo
      if not BigInteger.TryParse(ABigInteger, LBigInt) then
        raise Exception.CreateFmt('Virheellinen numero %s', [ABigInteger]);
      LDivisor := BigInteger.Create(Adivider);
      LRemainder := BigInteger.Create(0);

      // Lasketana ja Palautetaan
      LRemainder := LBigInt mod LDivisor;
      Result := LRemainder.AsInteger;
    end;

    var
      I: Integer;

    begin
      try
        I := BigIntegerStrMod('1234567890123456789123456789', 12345678);
        Writeln(I);
      except
        on E: Exception do
          Writeln(E.ClassName, ': ', E.Message);
      end;
      Readln;
    end.

**Comment by TommiPrami** [comment]
Did you use FastMM to check buffer overrun? Because just running it without FastMM debug-mode checks doesn't show the problem. Most likely by sheer luck, memory gets written in places where it doesn't matter. 

FastMM in debug mode puts known values at the end of the memory block. Is that known value changes it'll give error on freemem.

**Comment by rvelthuis** [comment]
Yes, I checked in several programs. There was a leak in `InternalRightShift`. Didn't find anything else. But I printed out your stack trace and will see what I can find. Seems to be `AllocNewMagnitude` and `MakeSize`. Will revisit.

**Comment by rvelthuis** [comment]
Tried with the latest FastMM4. And indeed, I get the same report. It seems to be `TryParse` causing the problem, as it doesn't happen if I use other ways to initialize `LBigInt`. Will see what I can do.

**Comment by TommiPrami** [comment]
Way cool!

I'll try to check that out too.

-tee-

**Comment by TommiPrami** [comment]
Checked that much that it behaves similarly built with purepascal-define. 

So it is not just error in ASM-optimization.

**Comment by rvelthuis** [comment]
Found quite a few buffer overruns (or actually badly dimensioned arrays). **Should all be fixed now** (crossing fingers). Took me a lot of grumbling and pulling hair. Time to see my hair stylist tomorrow, to see if she can save some of it. &lt;g&gt;

**Comment by TommiPrami** [comment]
Don't see the error anymore. So big thanks to you. Keep up the good work!
