### ISSUE TITLE
Possibly wrong date format

### ISSUE THREAD

**Issue by TommiPrami** [rvelthuis/BigNumbers#6]
Velthuis.BigDecimals.pas

    LongDateFormat: 'dddd, dd MMMMM yyyy HH:mm:ss';

maybe to

    LongDateFormat: 'dddd, dd MMMMM yyyy HH:nn:ss';

Months in time part seems wrong. (If more than less standard Delphi format(s))

**Comment by rvelthuis** [comment]
According to [MSDN](https://msdn.microsoft.com/en-gb/library/windows/desktop/dd318148(v=vs.85).aspx), `mm` is correct for minutes, not `nn`. AFAIK, Delphi usually gets these directly from the Windows registry. I think you are confusing these with `FormatDateTime` formatting codes. These are similar, but not the same.

**Comment by rvelthuis** [comment]
FWIW, in Tokyo, `TFormatSettings.Invariant.LongDateFormat` is exactly `'dddd, dd MMMMM yyyy HH:mm:ss'`.
