### ISSUE TITLE
FreePascal Support

### ISSUE THREAD

**Issue by Xor-el** [rvelthuis/BigNumbers#7]
First of all, I would like to commend the brilliant work you have done on this library.
I would also like to ask if there are any future plans to support FreePascal compiler??

**Comment by rvelthuis** [comment]
I will not do any FreePascal support myself. There are too many differences for me to make it work. But, as I wrote in my [article about BigIntegers](http://rvelthuis.de/programs/bigintegers.html#fpc), I did try. Despite the differences, it seems quite possible, but still a lot of work, so you are free to try it yourself.
